version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/laravel:cached
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
    depends_on:
      php-fpm:
        condition: service_started
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - .:/usr/local/laravel:cached
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql/mysql-server:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf:ro,umask=022
      - mysql:/var/lib/mysql:cached
    security_opt:
      - seccomp:unconfined
volumes:
  mysql:
